listen_addresses = ['172.30.0.2:5053']

# Only use Quad9 (no-log, non-profit, filtered)
# quad9-dnscrypt-ip4-filter-pri covers 3 anycast IPs (9.9.9.9 / 149.112.112.9 / 149.112.112.112)
server_names = ['quad9-dnscrypt-ip4-filter-pri']

# Disable ECS - do not forward client subnet to resolvers
block_ipv6 = false
block_unqualified = true
block_undelegated = true

[sources]
  [sources.public-resolvers]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    cache_file = '/config/public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
